version: "3.2"

services:
  ## Nginx Web Container ###
  nginx:
    build: ./images/nginx
    container_name: nginx
    volumes:
      - type: bind
        source: ./www
        target: /var/www/html
      - ./conf/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx/log:/var/log/nginx:rw
      - type: bind
        source: ./share-files
        target: /var/www/share-files
    ports:
      - "80:80"
      - "8080:80"
      - "8035:80"
    restart: always
    networks:
      - net-php71
    depends_on:
      - php71
    
  ### PHP FPM Container ###
  php71:
    build: ./images/php71
    container_name: php71
    volumes:
      - type: bind
        source: ./www
        target: /var/www/html
      - ./conf/php71/conf/php.ini:/etc/php7/php.ini:ro
      - ./conf/php71/conf/php-fpm.conf:/etc/php7/php-fpm.conf:ro
      - ./conf/php71/conf/conf.d/www.conf:/etc/php7/php-fpm.d/www.conf:ro
      - type: bind
        source: ./share-files
        target: /var/www/share-files
    expose:
      - "9000"
    restart: always
    networks:
      - net-php71
      - net-mysql
    depends_on:
      - mysql

  ### MYSQL Container ###
  mysql:
    build: ./images/mysql
    container_name: mysql
    volumes:
      - type: volume
        source: db-mysql
        target: /var/lib/mysql
        volume:
          nocopy: true
      - ./conf/mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
      - type: bind
        source: ./share-files
        target: /var/www/share-files
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - net-mysql

### Networks Setup ###
networks:
  net-php71:
    driver: bridge
  net-mysql:
    driver: bridge

### Volumes Setup ###
volumes:
  db-mysql:
    driver: local